/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/account/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["v1_account_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bank/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_bank_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["v1_bank_partial_update"];
        trace?: never;
    };
    "/api/v1/bank/reconciliations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_bank_reconciliations_list"];
        put?: never;
        post: operations["v1_bank_reconciliations_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_dashboard_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/expense-templates/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_expense_templates_list"];
        put?: never;
        post: operations["v1_expense_templates_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/expense-templates/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_expense_templates_retrieve"];
        put: operations["v1_expense_templates_update"];
        post?: never;
        delete: operations["v1_expense_templates_destroy"];
        options?: never;
        head?: never;
        patch: operations["v1_expense_templates_partial_update"];
        trace?: never;
    };
    "/api/v1/exports/backup.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_exports_backup.json_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exports/ledger.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_exports_ledger.csv_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_health_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/household/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_household_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["v1_household_partial_update"];
        trace?: never;
    };
    "/api/v1/household/leave/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_household_leave_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/household/members/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_household_members_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/household/transfer-ownership/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_household_transfer_ownership_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/income-plans/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_income_plans_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/income-plans/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_income_plans_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/income-plans/{id}/receive/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_income_plans_receive_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/income-templates/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_income_templates_list"];
        put?: never;
        post: operations["v1_income_templates_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/income-templates/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_income_templates_retrieve"];
        put: operations["v1_income_templates_update"];
        post?: never;
        delete: operations["v1_income_templates_destroy"];
        options?: never;
        head?: never;
        patch: operations["v1_income_templates_partial_update"];
        trace?: never;
    };
    "/api/v1/invitations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_invitations_list"];
        put?: never;
        post: operations["v1_invitations_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_invitations_retrieve"];
        put?: never;
        post?: never;
        delete: operations["v1_invitations_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations/{token}/accept/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_invitations_accept_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ledger/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_ledger_list"];
        put?: never;
        post: operations["v1_ledger_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ledger/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_ledger_retrieve"];
        put: operations["v1_ledger_update"];
        post?: never;
        delete: operations["v1_ledger_destroy"];
        options?: never;
        head?: never;
        patch: operations["v1_ledger_partial_update"];
        trace?: never;
    };
    "/api/v1/months/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_months_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/months/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_months_retrieve"];
        put?: never;
        post?: never;
        delete: operations["v1_months_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/months/{id}/summary/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_months_summary_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/months/by-label/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_months_by_label_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/months/current/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_months_current_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/months/generate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_months_generate_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/months/rollover-preview/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_months_rollover_preview_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_notifications_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_notifications_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/{id}/read/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_notifications_read_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/read_all/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_notifications_read_all_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/onboarding/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_onboarding_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/personal-expenses/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_personal_expenses_list"];
        put?: never;
        post: operations["v1_personal_expenses_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/personal-expenses/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_personal_expenses_retrieve"];
        put: operations["v1_personal_expenses_update"];
        post?: never;
        delete: operations["v1_personal_expenses_destroy"];
        options?: never;
        head?: never;
        patch: operations["v1_personal_expenses_partial_update"];
        trace?: never;
    };
    "/api/v1/planned-expenses/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_planned_expenses_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/planned-expenses/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_planned_expenses_retrieve"];
        put: operations["v1_planned_expenses_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["v1_planned_expenses_partial_update"];
        trace?: never;
    };
    "/api/v1/planned-expenses/{id}/payments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_planned_expenses_payments_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/planned-expenses/reorder/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_planned_expenses_reorder_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/preferences/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_preferences_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["v1_preferences_partial_update"];
        trace?: never;
    };
    "/api/v1/reports/trends/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_reports_trends_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/savings-goals/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_savings_goals_list"];
        put?: never;
        post: operations["v1_savings_goals_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/savings-goals/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_savings_goals_retrieve"];
        put: operations["v1_savings_goals_update"];
        post?: never;
        delete: operations["v1_savings_goals_destroy"];
        options?: never;
        head?: never;
        patch: operations["v1_savings_goals_partial_update"];
        trace?: never;
    };
    "/api/v1/savings-movements/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_savings_movements_list"];
        put?: never;
        post: operations["v1_savings_movements_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/savings-movements/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_savings_movements_retrieve"];
        put: operations["v1_savings_movements_update"];
        post?: never;
        delete: operations["v1_savings_movements_destroy"];
        options?: never;
        head?: never;
        patch: operations["v1_savings_movements_partial_update"];
        trace?: never;
    };
    "/api/v1/session/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_session_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description * `savings` - Move to savings
         *     * `carryover` - Carry to next month
         * @enum {string}
         */
        ActionEnum: "savings" | "carryover";
        BankAccount: {
            readonly id: number;
            name?: string;
            /** Format: decimal */
            opening_balance: string;
            /** Format: date */
            opening_date: string;
            /** Format: double */
            readonly calculated_balance: number;
        };
        BankReconciliation: {
            readonly id: number;
            /** Format: date */
            date: string;
            /** Format: decimal */
            actual_balance: string;
            /** Format: decimal */
            calculated_balance: string;
            /** Format: decimal */
            variance: string;
            notes?: string;
            /** Format: date-time */
            readonly created_at: string;
        };
        BillRolloverInput: {
            planned_expense: number;
            destination_goal: number;
        };
        /**
         * @description * `credit` - Credit
         *     * `debit` - Debit
         * @enum {string}
         */
        DirectionEnum: "credit" | "debit";
        /**
         * @description * `income` - Income
         *     * `household_expense` - Household expense
         *     * `personal_expense` - Personal expense
         *     * `adjustment` - Bank adjustment
         * @enum {string}
         */
        EntryTypeEnum: "income" | "household_expense" | "personal_expense" | "adjustment";
        ExpenseSetup: {
            name: string;
            /** Format: double */
            expected_amount: number;
            due_day: number;
            /** @default 3 */
            reminder_lead_days: number;
        };
        Household: {
            readonly id: number;
            name: string;
            readonly owner: components["schemas"]["User"];
            readonly currency: string;
            readonly timezone: string;
            /** Format: decimal */
            monthly_savings_target?: string;
            /** Format: int64 */
            savings_reminder_day?: number;
            readonly onboarding_complete: boolean;
        };
        IncomeReceipt: {
            /** Format: double */
            amount?: number;
            /** Format: date */
            date?: string;
            savings_goal?: number | null;
        };
        IncomeSetup: {
            name: string;
            /** Format: double */
            amount: number;
        };
        Invitation: {
            readonly id: number;
            /** Format: email */
            email: string;
            readonly status: components["schemas"]["StatusEnum"];
            /** Format: date-time */
            readonly expires_at: string;
            readonly invite_url: string;
            /** Format: date-time */
            readonly created_at: string;
        };
        LedgerEntry: {
            readonly id: number;
            period: number;
            planned_income?: number | null;
            planned_expense?: number | null;
            entry_type: components["schemas"]["EntryTypeEnum"];
            direction: components["schemas"]["DirectionEnum"];
            /** Format: date */
            date: string;
            /** Format: decimal */
            amount: string;
            description: string;
            notes?: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        Membership: {
            readonly id: number;
            readonly user: components["schemas"]["User"];
            readonly role: components["schemas"]["RoleEnum"];
            readonly is_active: boolean;
            /** Format: date-time */
            readonly created_at: string;
        };
        MonthGenerateInput: {
            year?: number;
            month?: number;
            rollover?: components["schemas"]["MonthRolloverInput"];
        };
        MonthRolloverInput: {
            bill_allocations?: components["schemas"]["BillRolloverInput"][];
            safe_to_spend?: components["schemas"]["SafeToSpendRolloverInput"] | null;
        };
        MonthlyIncomePlan: {
            readonly id: number;
            name: string;
            /** Format: decimal */
            planned_amount: string;
            /** Format: double */
            readonly received_amount: number;
        };
        MonthlyPeriod: {
            readonly id: number;
            /** Format: int64 */
            year: number;
            /** Format: int64 */
            month: number;
            readonly label: string;
            /** Format: decimal */
            savings_target?: string;
            readonly fixed_savings_allocated: boolean;
            /** Format: double */
            readonly safe_to_spend_carryover: number;
            readonly income_plans: components["schemas"]["MonthlyIncomePlan"][];
            readonly planned_expenses: components["schemas"]["PlannedExpense"][];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        Notification: {
            readonly id: number;
            readonly kind: components["schemas"]["NotificationKindEnum"];
            readonly title: string;
            readonly message: string;
            readonly action_url: string;
            /** Format: date-time */
            read_at?: string | null;
            /** Format: date-time */
            readonly created_at: string;
        };
        /**
         * @description * `bill_due` - Bill due
         *     * `bill_overdue` - Bill overdue
         *     * `savings` - Savings
         *     * `invitation` - Invitation
         *     * `system` - System
         * @enum {string}
         */
        NotificationKindEnum: "bill_due" | "bill_overdue" | "savings" | "invitation" | "system";
        Onboarding: {
            household_name: string;
            /** @default Main Bank */
            bank_name: string;
            /** Format: double */
            opening_balance: number;
            /** Format: date */
            opening_date: string;
            /** Format: double */
            monthly_savings_target: number;
            incomes: components["schemas"]["IncomeSetup"][];
            expenses: components["schemas"]["ExpenseSetup"][];
            savings_goals: components["schemas"]["SavingsGoalSetup"][];
        };
        OwnershipTransfer: {
            membership_id: number;
        };
        PaginatedInvitationList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Invitation"][];
        };
        PaginatedLedgerEntryList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["LedgerEntry"][];
        };
        PaginatedMonthlyIncomePlanList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["MonthlyIncomePlan"][];
        };
        PaginatedMonthlyPeriodList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["MonthlyPeriod"][];
        };
        PaginatedNotificationList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Notification"][];
        };
        PaginatedPersonalExpenseList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["PersonalExpense"][];
        };
        PaginatedPlannedExpenseList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["PlannedExpense"][];
        };
        PaginatedRecurringExpenseList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["RecurringExpense"][];
        };
        PaginatedRecurringIncomeList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["RecurringIncome"][];
        };
        PaginatedSavingsGoalList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["SavingsGoal"][];
        };
        PaginatedSavingsMovementList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["SavingsMovement"][];
        };
        PatchedBankAccount: {
            readonly id?: number;
            name?: string;
            /** Format: decimal */
            opening_balance?: string;
            /** Format: date */
            opening_date?: string;
            /** Format: double */
            readonly calculated_balance?: number;
        };
        PatchedHousehold: {
            readonly id?: number;
            name?: string;
            readonly owner?: components["schemas"]["User"];
            readonly currency?: string;
            readonly timezone?: string;
            /** Format: decimal */
            monthly_savings_target?: string;
            /** Format: int64 */
            savings_reminder_day?: number;
            readonly onboarding_complete?: boolean;
        };
        PatchedLedgerEntry: {
            readonly id?: number;
            period?: number;
            planned_income?: number | null;
            planned_expense?: number | null;
            entry_type?: components["schemas"]["EntryTypeEnum"];
            direction?: components["schemas"]["DirectionEnum"];
            /** Format: date */
            date?: string;
            /** Format: decimal */
            amount?: string;
            description?: string;
            notes?: string;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        PatchedPersonalExpense: {
            readonly id?: number;
            period?: number;
            /** Format: date */
            date?: string;
            /** Format: decimal */
            amount?: string;
            description?: string;
            notes?: string;
            /** Format: date-time */
            readonly created_at?: string;
        };
        PatchedPlannedExpense: {
            readonly id?: number;
            name?: string;
            /** Format: decimal */
            expected_amount?: string;
            /** Format: date */
            due_date?: string;
            /** Format: int64 */
            reminder_lead_days?: number;
            readonly display_order?: number;
            /** Format: double */
            readonly actual_paid_amount?: number;
            /** Format: double */
            readonly carryover_credit?: number;
            /** Format: double */
            readonly paid_amount?: number;
            /** Format: double */
            readonly remaining_amount?: number;
            /** Format: double */
            readonly overpaid_amount?: number;
            readonly status?: string;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        PatchedRecurringExpense: {
            readonly id?: number;
            name?: string;
            /** Format: decimal */
            expected_amount?: string;
            /** Format: int64 */
            due_day?: number;
            /** Format: int64 */
            reminder_lead_days?: number;
            active?: boolean;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        PatchedRecurringIncome: {
            readonly id?: number;
            name?: string;
            /** Format: decimal */
            amount?: string;
            active?: boolean;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        PatchedSavingsGoal: {
            readonly id?: number;
            name?: string;
            /** Format: double */
            opening_balance?: number;
            /** Format: double */
            target_amount?: number | null;
            active?: boolean;
            /** Format: double */
            readonly balance?: number;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        PatchedSavingsMovement: {
            readonly id?: number;
            period?: number | null;
            kind?: components["schemas"]["SavingsMovementKindEnum"];
            source_goal?: number | null;
            destination_goal?: number | null;
            /** Format: date */
            date?: string;
            /** Format: decimal */
            amount?: string;
            notes?: string;
            readonly rollover_allocation?: number | null;
            /** Format: date-time */
            readonly created_at?: string;
        };
        PatchedUserPreference: {
            preferred_language?: components["schemas"]["PreferredLanguageEnum"];
            tour_completed?: boolean;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        PersonalExpense: {
            readonly id: number;
            period: number;
            /** Format: date */
            date: string;
            /** Format: decimal */
            amount: string;
            description: string;
            notes?: string;
            /** Format: date-time */
            readonly created_at: string;
        };
        PlannedExpense: {
            readonly id: number;
            name: string;
            /** Format: decimal */
            expected_amount: string;
            /** Format: date */
            due_date: string;
            /** Format: int64 */
            reminder_lead_days?: number;
            readonly display_order: number;
            /** Format: double */
            readonly actual_paid_amount: number;
            /** Format: double */
            readonly carryover_credit: number;
            /** Format: double */
            readonly paid_amount: number;
            /** Format: double */
            readonly remaining_amount: number;
            /** Format: double */
            readonly overpaid_amount: number;
            readonly status: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description * `en` - English
         *     * `ur` - Urdu
         * @enum {string}
         */
        PreferredLanguageEnum: "en" | "ur";
        ReconciliationInput: {
            /** Format: date */
            date?: string;
            /** Format: double */
            actual_balance: number;
            notes?: string;
            /** @default false */
            post_adjustment: boolean;
        };
        RecurringExpense: {
            readonly id: number;
            name: string;
            /** Format: decimal */
            expected_amount: string;
            /** Format: int64 */
            due_day?: number;
            /** Format: int64 */
            reminder_lead_days?: number;
            active?: boolean;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        RecurringIncome: {
            readonly id: number;
            name: string;
            /** Format: decimal */
            amount: string;
            active?: boolean;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description * `owner` - Owner
         *     * `member` - Member
         * @enum {string}
         */
        RoleEnum: "owner" | "member";
        SafeToSpendRolloverInput: {
            action: components["schemas"]["ActionEnum"];
            destination_goal?: number | null;
        };
        SavingsGoal: {
            readonly id: number;
            name: string;
            /** Format: double */
            opening_balance: number;
            /** Format: double */
            target_amount?: number | null;
            active?: boolean;
            /** Format: double */
            readonly balance: number;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        SavingsGoalSetup: {
            name: string;
            /**
             * Format: double
             * @default 0
             */
            opening_balance: number;
            /** Format: double */
            target_amount?: number | null;
        };
        SavingsMovement: {
            readonly id: number;
            period?: number | null;
            kind: components["schemas"]["SavingsMovementKindEnum"];
            source_goal?: number | null;
            destination_goal?: number | null;
            /** Format: date */
            date: string;
            /** Format: decimal */
            amount: string;
            notes?: string;
            readonly rollover_allocation: number | null;
            /** Format: date-time */
            readonly created_at: string;
        };
        /**
         * @description * `contribution` - Contribution
         *     * `withdrawal` - Withdrawal
         *     * `transfer` - Transfer
         *     * `allocation` - Internal allocation
         * @enum {string}
         */
        SavingsMovementKindEnum: "contribution" | "withdrawal" | "transfer" | "allocation";
        /**
         * @description * `pending` - Pending
         *     * `accepted` - Accepted
         *     * `revoked` - Revoked
         *     * `expired` - Expired
         * @enum {string}
         */
        StatusEnum: "pending" | "accepted" | "revoked" | "expired";
        User: {
            readonly id: number;
            /** Format: email */
            readonly email: string;
            readonly name: string;
        };
        UserPreference: {
            preferred_language?: components["schemas"]["PreferredLanguageEnum"];
            tour_completed?: boolean;
            /** Format: date-time */
            readonly updated_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    v1_account_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_bank_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankAccount"];
                };
            };
        };
    };
    v1_bank_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedBankAccount"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedBankAccount"];
                "multipart/form-data": components["schemas"]["PatchedBankAccount"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankAccount"];
                };
            };
        };
    };
    v1_bank_reconciliations_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankReconciliation"][];
                };
            };
        };
    };
    v1_bank_reconciliations_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReconciliationInput"];
                "application/x-www-form-urlencoded": components["schemas"]["ReconciliationInput"];
                "multipart/form-data": components["schemas"]["ReconciliationInput"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankReconciliation"];
                };
            };
        };
    };
    v1_dashboard_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    v1_expense_templates_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedRecurringExpenseList"];
                };
            };
        };
    };
    v1_expense_templates_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecurringExpense"];
                "application/x-www-form-urlencoded": components["schemas"]["RecurringExpense"];
                "multipart/form-data": components["schemas"]["RecurringExpense"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringExpense"];
                };
            };
        };
    };
    v1_expense_templates_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this recurring expense. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringExpense"];
                };
            };
        };
    };
    v1_expense_templates_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this recurring expense. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecurringExpense"];
                "application/x-www-form-urlencoded": components["schemas"]["RecurringExpense"];
                "multipart/form-data": components["schemas"]["RecurringExpense"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringExpense"];
                };
            };
        };
    };
    v1_expense_templates_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this recurring expense. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_expense_templates_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this recurring expense. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedRecurringExpense"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedRecurringExpense"];
                "multipart/form-data": components["schemas"]["PatchedRecurringExpense"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringExpense"];
                };
            };
        };
    };
    "v1_exports_backup.json_retrieve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    "v1_exports_ledger.csv_retrieve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
        };
    };
    v1_health_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    v1_household_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Household"];
                };
            };
        };
    };
    v1_household_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedHousehold"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedHousehold"];
                "multipart/form-data": components["schemas"]["PatchedHousehold"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Household"];
                };
            };
        };
    };
    v1_household_leave_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_household_members_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Membership"][];
                };
            };
        };
    };
    v1_household_transfer_ownership_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OwnershipTransfer"];
                "application/x-www-form-urlencoded": components["schemas"]["OwnershipTransfer"];
                "multipart/form-data": components["schemas"]["OwnershipTransfer"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    v1_income_plans_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedMonthlyIncomePlanList"];
                };
            };
        };
    };
    v1_income_plans_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this monthly income plan. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyIncomePlan"];
                };
            };
        };
    };
    v1_income_plans_receive_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this monthly income plan. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["IncomeReceipt"];
                "application/x-www-form-urlencoded": components["schemas"]["IncomeReceipt"];
                "multipart/form-data": components["schemas"]["IncomeReceipt"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LedgerEntry"];
                };
            };
        };
    };
    v1_income_templates_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedRecurringIncomeList"];
                };
            };
        };
    };
    v1_income_templates_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecurringIncome"];
                "application/x-www-form-urlencoded": components["schemas"]["RecurringIncome"];
                "multipart/form-data": components["schemas"]["RecurringIncome"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringIncome"];
                };
            };
        };
    };
    v1_income_templates_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this recurring income. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringIncome"];
                };
            };
        };
    };
    v1_income_templates_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this recurring income. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecurringIncome"];
                "application/x-www-form-urlencoded": components["schemas"]["RecurringIncome"];
                "multipart/form-data": components["schemas"]["RecurringIncome"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringIncome"];
                };
            };
        };
    };
    v1_income_templates_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this recurring income. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_income_templates_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this recurring income. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedRecurringIncome"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedRecurringIncome"];
                "multipart/form-data": components["schemas"]["PatchedRecurringIncome"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringIncome"];
                };
            };
        };
    };
    v1_invitations_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedInvitationList"];
                };
            };
        };
    };
    v1_invitations_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Invitation"];
                "application/x-www-form-urlencoded": components["schemas"]["Invitation"];
                "multipart/form-data": components["schemas"]["Invitation"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invitation"];
                };
            };
        };
    };
    v1_invitations_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this household invitation. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invitation"];
                };
            };
        };
    };
    v1_invitations_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this household invitation. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_invitations_accept_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    v1_ledger_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedLedgerEntryList"];
                };
            };
        };
    };
    v1_ledger_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LedgerEntry"];
                "application/x-www-form-urlencoded": components["schemas"]["LedgerEntry"];
                "multipart/form-data": components["schemas"]["LedgerEntry"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LedgerEntry"];
                };
            };
        };
    };
    v1_ledger_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this ledger entry. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LedgerEntry"];
                };
            };
        };
    };
    v1_ledger_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this ledger entry. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LedgerEntry"];
                "application/x-www-form-urlencoded": components["schemas"]["LedgerEntry"];
                "multipart/form-data": components["schemas"]["LedgerEntry"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LedgerEntry"];
                };
            };
        };
    };
    v1_ledger_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this ledger entry. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_ledger_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this ledger entry. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedLedgerEntry"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedLedgerEntry"];
                "multipart/form-data": components["schemas"]["PatchedLedgerEntry"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LedgerEntry"];
                };
            };
        };
    };
    v1_months_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedMonthlyPeriodList"];
                };
            };
        };
    };
    v1_months_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this monthly period. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyPeriod"];
                };
            };
        };
    };
    v1_months_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this monthly period. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_months_summary_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this monthly period. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyPeriod"];
                };
            };
        };
    };
    v1_months_by_label_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyPeriod"];
                };
            };
        };
    };
    v1_months_current_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyPeriod"];
                };
            };
        };
    };
    v1_months_generate_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["MonthGenerateInput"];
                "application/x-www-form-urlencoded": components["schemas"]["MonthGenerateInput"];
                "multipart/form-data": components["schemas"]["MonthGenerateInput"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyPeriod"];
                };
            };
        };
    };
    v1_months_rollover_preview_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyPeriod"];
                };
            };
        };
    };
    v1_notifications_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedNotificationList"];
                };
            };
        };
    };
    v1_notifications_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this notification. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"];
                };
            };
        };
    };
    v1_notifications_read_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this notification. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Notification"];
                "application/x-www-form-urlencoded": components["schemas"]["Notification"];
                "multipart/form-data": components["schemas"]["Notification"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"];
                };
            };
        };
    };
    v1_notifications_read_all_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Notification"];
                "application/x-www-form-urlencoded": components["schemas"]["Notification"];
                "multipart/form-data": components["schemas"]["Notification"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"];
                };
            };
        };
    };
    v1_onboarding_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Onboarding"];
                "application/x-www-form-urlencoded": components["schemas"]["Onboarding"];
                "multipart/form-data": components["schemas"]["Onboarding"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Household"];
                };
            };
        };
    };
    v1_personal_expenses_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPersonalExpenseList"];
                };
            };
        };
    };
    v1_personal_expenses_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonalExpense"];
                "application/x-www-form-urlencoded": components["schemas"]["PersonalExpense"];
                "multipart/form-data": components["schemas"]["PersonalExpense"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonalExpense"];
                };
            };
        };
    };
    v1_personal_expenses_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this ledger entry. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonalExpense"];
                };
            };
        };
    };
    v1_personal_expenses_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this ledger entry. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonalExpense"];
                "application/x-www-form-urlencoded": components["schemas"]["PersonalExpense"];
                "multipart/form-data": components["schemas"]["PersonalExpense"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonalExpense"];
                };
            };
        };
    };
    v1_personal_expenses_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this ledger entry. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_personal_expenses_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this ledger entry. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedPersonalExpense"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedPersonalExpense"];
                "multipart/form-data": components["schemas"]["PatchedPersonalExpense"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonalExpense"];
                };
            };
        };
    };
    v1_planned_expenses_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPlannedExpenseList"];
                };
            };
        };
    };
    v1_planned_expenses_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this planned expense. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlannedExpense"];
                };
            };
        };
    };
    v1_planned_expenses_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this planned expense. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlannedExpense"];
                "application/x-www-form-urlencoded": components["schemas"]["PlannedExpense"];
                "multipart/form-data": components["schemas"]["PlannedExpense"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlannedExpense"];
                };
            };
        };
    };
    v1_planned_expenses_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this planned expense. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedPlannedExpense"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedPlannedExpense"];
                "multipart/form-data": components["schemas"]["PatchedPlannedExpense"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlannedExpense"];
                };
            };
        };
    };
    v1_planned_expenses_payments_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this planned expense. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlannedExpense"];
                "application/x-www-form-urlencoded": components["schemas"]["PlannedExpense"];
                "multipart/form-data": components["schemas"]["PlannedExpense"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlannedExpense"];
                };
            };
        };
    };
    v1_planned_expenses_reorder_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlannedExpense"];
                "application/x-www-form-urlencoded": components["schemas"]["PlannedExpense"];
                "multipart/form-data": components["schemas"]["PlannedExpense"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlannedExpense"];
                };
            };
        };
    };
    v1_preferences_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPreference"];
                };
            };
        };
    };
    v1_preferences_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUserPreference"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUserPreference"];
                "multipart/form-data": components["schemas"]["PatchedUserPreference"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPreference"];
                };
            };
        };
    };
    v1_reports_trends_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    v1_savings_goals_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSavingsGoalList"];
                };
            };
        };
    };
    v1_savings_goals_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavingsGoal"];
                "application/x-www-form-urlencoded": components["schemas"]["SavingsGoal"];
                "multipart/form-data": components["schemas"]["SavingsGoal"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavingsGoal"];
                };
            };
        };
    };
    v1_savings_goals_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this savings goal. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavingsGoal"];
                };
            };
        };
    };
    v1_savings_goals_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this savings goal. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavingsGoal"];
                "application/x-www-form-urlencoded": components["schemas"]["SavingsGoal"];
                "multipart/form-data": components["schemas"]["SavingsGoal"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavingsGoal"];
                };
            };
        };
    };
    v1_savings_goals_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this savings goal. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_savings_goals_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this savings goal. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedSavingsGoal"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedSavingsGoal"];
                "multipart/form-data": components["schemas"]["PatchedSavingsGoal"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavingsGoal"];
                };
            };
        };
    };
    v1_savings_movements_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSavingsMovementList"];
                };
            };
        };
    };
    v1_savings_movements_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavingsMovement"];
                "application/x-www-form-urlencoded": components["schemas"]["SavingsMovement"];
                "multipart/form-data": components["schemas"]["SavingsMovement"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavingsMovement"];
                };
            };
        };
    };
    v1_savings_movements_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this savings movement. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavingsMovement"];
                };
            };
        };
    };
    v1_savings_movements_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this savings movement. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavingsMovement"];
                "application/x-www-form-urlencoded": components["schemas"]["SavingsMovement"];
                "multipart/form-data": components["schemas"]["SavingsMovement"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavingsMovement"];
                };
            };
        };
    };
    v1_savings_movements_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this savings movement. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_savings_movements_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this savings movement. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedSavingsMovement"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedSavingsMovement"];
                "multipart/form-data": components["schemas"]["PatchedSavingsMovement"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavingsMovement"];
                };
            };
        };
    };
    v1_session_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
