# Generated by Django 5.2.16 on 2026-07-30 08:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Main Bank', max_length=120)),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('opening_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('actual_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('calculated_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('variance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='finance.bankaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_reconciliations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('currency', models.CharField(default='PKR', editable=False, max_length=3)),
                ('timezone', models.CharField(default='Asia/Karachi', editable=False, max_length=64)),
                ('monthly_savings_target', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('savings_reminder_day', models.PositiveSmallIntegerField(default=25)),
                ('onboarding_complete', models.BooleanField(default=False)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='owned_household', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='household',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='finance.household'),
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_audit_events', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='finance.household')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HouseholdInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_household_invitations', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='finance.household')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_household_invitations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('member', 'Member')], max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='finance.household')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance_membership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('savings_target', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='finance.household')),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyIncomePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_plans', to='finance.monthlyperiod')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('bill_due', 'Bill due'), ('bill_overdue', 'Bill overdue'), ('savings', 'Savings'), ('invitation', 'Invitation'), ('system', 'System')], max_length=24)),
                ('title', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('action_url', models.CharField(blank=True, max_length=255)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='finance.household')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlannedExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('due_date', models.DateField()),
                ('reminder_lead_days', models.PositiveSmallIntegerField(default=3)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_expenses', to='finance.monthlyperiod')),
            ],
            options={
                'ordering': ['due_date', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('income', 'Income'), ('household_expense', 'Household expense'), ('personal_expense', 'Personal expense'), ('adjustment', 'Bank adjustment')], max_length=32)),
                ('direction', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=8)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.CharField(max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='finance.household')),
                ('planned_income', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='finance.monthlyincomeplan')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='finance.monthlyperiod')),
                ('planned_expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='finance.plannedexpense')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurringExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('due_day', models.PositiveSmallIntegerField(default=1)),
                ('reminder_lead_days', models.PositiveSmallIntegerField(default=3)),
                ('active', models.BooleanField(default=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_templates', to='finance.household')),
            ],
            options={
                'ordering': ['due_day', 'name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='plannedexpense',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_snapshots', to='finance.recurringexpense'),
        ),
        migrations.CreateModel(
            name='RecurringIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('active', models.BooleanField(default=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_templates', to='finance.household')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='monthlyincomeplan',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_snapshots', to='finance.recurringincome'),
        ),
        migrations.CreateModel(
            name='ReminderDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=180, unique=True)),
                ('channel', models.CharField(max_length=16)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('error', models.TextField(blank=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_deliveries', to='finance.household')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_reminder_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SavingsGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('target_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('active', models.BooleanField(default=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_goals', to='finance.household')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SavingsMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('contribution', 'Contribution'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer')], max_length=16)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='savings_movements', to=settings.AUTH_USER_MODEL)),
                ('destination_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_movements', to='finance.savingsgoal')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_movements', to='finance.household')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='savings_movements', to='finance.monthlyperiod')),
                ('source_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_movements', to='finance.savingsgoal')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='household',
            constraint=models.CheckConstraint(condition=models.Q(('monthly_savings_target__gte', 0)), name='household_nonnegative_savings_target'),
        ),
        migrations.AddConstraint(
            model_name='household',
            constraint=models.CheckConstraint(condition=models.Q(('savings_reminder_day__gte', 1), ('savings_reminder_day__lte', 28)), name='household_valid_savings_reminder_day'),
        ),
        migrations.AddConstraint(
            model_name='householdinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('household', 'email'), name='one_pending_invite_per_household_email'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['household', 'is_active'], name='finance_mem_househo_a08304_idx'),
        ),
        migrations.AddConstraint(
            model_name='monthlyperiod',
            constraint=models.UniqueConstraint(fields=('household', 'year', 'month'), name='unique_household_month'),
        ),
        migrations.AddConstraint(
            model_name='monthlyperiod',
            constraint=models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='period_valid_month'),
        ),
        migrations.AddConstraint(
            model_name='monthlyperiod',
            constraint=models.CheckConstraint(condition=models.Q(('savings_target__gte', 0)), name='period_nonnegative_savings_target'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'read_at'], name='finance_not_recipie_b9d051_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['household', 'date'], name='finance_led_househo_c4da97_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['period', 'entry_type'], name='finance_led_period__ba5c3f_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ledger_entry_positive_amount'),
        ),
        migrations.AddConstraint(
            model_name='recurringexpense',
            constraint=models.CheckConstraint(condition=models.Q(('expected_amount__gt', 0)), name='recurring_expense_positive_amount'),
        ),
        migrations.AddConstraint(
            model_name='recurringexpense',
            constraint=models.CheckConstraint(condition=models.Q(('due_day__gte', 1), ('due_day__lte', 31)), name='recurring_expense_valid_due_day'),
        ),
        migrations.AddConstraint(
            model_name='recurringexpense',
            constraint=models.CheckConstraint(condition=models.Q(('reminder_lead_days__lte', 31)), name='recurring_expense_valid_lead_days'),
        ),
        migrations.AddConstraint(
            model_name='plannedexpense',
            constraint=models.CheckConstraint(condition=models.Q(('expected_amount__gt', 0)), name='planned_expense_positive_amount'),
        ),
        migrations.AddConstraint(
            model_name='recurringincome',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='recurring_income_positive_amount'),
        ),
        migrations.AddConstraint(
            model_name='monthlyincomeplan',
            constraint=models.CheckConstraint(condition=models.Q(('planned_amount__gt', 0)), name='monthly_income_plan_positive'),
        ),
        migrations.AddConstraint(
            model_name='savingsgoal',
            constraint=models.UniqueConstraint(fields=('household', 'name'), name='unique_savings_goal_name'),
        ),
        migrations.AddConstraint(
            model_name='savingsgoal',
            constraint=models.CheckConstraint(condition=models.Q(('opening_balance__gte', 0)), name='savings_goal_nonnegative_opening'),
        ),
        migrations.AddConstraint(
            model_name='savingsgoal',
            constraint=models.CheckConstraint(condition=models.Q(('target_amount__isnull', True), ('target_amount__gt', 0), _connector='OR'), name='savings_goal_positive_target'),
        ),
        migrations.AddConstraint(
            model_name='savingsmovement',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='savings_movement_positive_amount'),
        ),
    ]
