# Generated by Django 5.2.16 on 2026-08-01 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_userpreference_tour_completed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsmovement',
            name='kind',
            field=models.CharField(choices=[('contribution', 'Contribution'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('allocation', 'Internal allocation')], max_length=16),
        ),
        migrations.CreateModel(
            name='RolloverAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_kind', models.CharField(choices=[('household_remainder', 'Household bill remainder'), ('safe_to_spend', 'Safe to spend')], max_length=24)),
                ('source_key', models.CharField(max_length=64)),
                ('action', models.CharField(choices=[('savings', 'Move to savings'), ('carryover', 'Carry to next month')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_rollover_allocations', to=settings.AUTH_USER_MODEL)),
                ('destination_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rollover_allocations', to='finance.savingsgoal')),
                ('destination_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_rollover_allocations', to='finance.monthlyperiod')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollover_allocations', to='finance.household')),
                ('source_expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='savings_rollovers', to='finance.plannedexpense')),
                ('source_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_rollover_allocations', to='finance.monthlyperiod')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='savingsmovement',
            name='rollover_allocation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='savings_movement', to='finance.rolloverallocation'),
        ),
        migrations.AddConstraint(
            model_name='rolloverallocation',
            constraint=models.UniqueConstraint(fields=('source_period', 'source_key'), name='unique_period_rollover_source'),
        ),
        migrations.AddConstraint(
            model_name='rolloverallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='rollover_allocation_positive_amount'),
        ),
        migrations.AddConstraint(
            model_name='rolloverallocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('action', 'savings'), ('destination_goal__isnull', False)), models.Q(('action', 'carryover'), ('destination_goal__isnull', True)), _connector='OR'), name='rollover_action_matches_goal'),
        ),
    ]
