# Generated by Django 5.2.16 on 2026-08-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_savingsmovement_kind_rolloverallocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolloverallocation',
            name='source_kind',
            field=models.CharField(choices=[('household_remainder', 'Household bill remainder'), ('safe_to_spend', 'Safe to spend'), ('fixed_savings', 'Fixed monthly savings')], max_length=24),
        ),
    ]
